/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#b32827',
        'on-primary-fixed-variant': '#00504f',
        background: '#fff8f7',
        'inverse-on-surface': '#ffedeb',
        'on-primary-container': '#003938',
        'surface-tint': '#006a69',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-primary': '#68d8d6',
        outline: '#6d7979',
        'on-surface': '#410004',
        'on-secondary-container': '#746332',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ffcfcb',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'surface-variant': '#ffdad7',
        'outline-variant': '#bcc9c8',
        'surface-container-low': '#fff0ef',
        'primary-fixed-dim': '#68d8d6',
        'on-primary-fixed': '#002020',
        'secondary-fixed-dim': '#dbc58b',
        'tertiary-fixed': '#ffdad6',
        'on-surface-variant': '#3d4949',
        'secondary-container': '#f8e0a4',
        'on-error-container': '#93000a',
        primary: '#006a69',
        'tertiary-fixed-dim': '#ffb4ac',
        'on-tertiary-container': '#6b0007',
        'inverse-surface': '#611113',
        surface: '#fff8f7',
        'on-background': '#410004',
        'surface-bright': '#fff8f7',
        'primary-container': '#31aaa9',
        'on-tertiary-fixed': '#410003',
        'on-tertiary-fixed-variant': '#900a12',
        'secondary-fixed': '#f8e0a4',
        'surface-container-high': '#ffe2df',
        secondary: '#6e5d2d',
        'primary-fixed': '#86f4f3',
        'on-tertiary': '#ffffff',
        'surface-container': '#ffe9e7',
        'surface-container-highest': '#ffdad7',
        'tertiary-container': '#ff695f',
        'on-secondary-fixed-variant': '#544518',
      },
      spacing: {
        'space-xl': '2.5rem',
        'margin-mobile': '1rem',
        margin: '2rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        gutter: '1.5rem',
        'space-margin': '2rem',
      },
      fontFamily: {
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 1px 8px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}
